version: 2.1
jobs:
  analytics-service-build:
    machine: true
    steps:
    - checkout
    - run: git clone https://github.com/project-sunbird/sunbird-analytics-core
    - restore_cache:
        keys: 
          - dp-dependency-cache-{{ checksum "pom.xml" }}
    - run: cd sunbird-analytics-core/analytics-core && mvn install -DskipTests
    - run:
        name: lpa-api-build
        command: mvn clean scoverage:report
    - save_cache:
        key: dp-dependency-cache-{{ checksum "pom.xml" }}
        paths: ~/.m2
#    - run:
#        name: sonar
#        command: |
#          mvn -X sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-analytics-service -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.scala.coverage.reportPaths=/home/circleci/project/target/scoverage.xml

workflows:
  version: 2.1
  workflow:
    jobs:
    - analytics-service-build